<?php $cats=array(array (
  'title' => 'Для кухни',
  'id' => 'santehnika-online.ru/smesiteli/na_kukhnyu/',
  'url' => 'http://santehnika-online.ru/smesiteli/na_kukhnyu/',
  'brands' => 
  array (
    0 => 'BelBagno',
    1 => 'Bravat',
    2 => 'Cezares',
    3 => 'Edelform',
    4 => 'Fima Carlo Frattini',
    5 => 'Grohe',
    6 => 'Hansgrohe',
    7 => 'Ideal Standard',
    8 => 'Iddis',
    9 => 'Jacob Delafon',
    10 => 'Kludi',
    11 => 'Lemark',
    12 => 'Migliore',
    13 => 'Nobili',
    14 => 'Oras',
    15 => 'Roca',
    16 => 'Seaman',
  ),
));?>