<?php $cats=array(array (
  'title' => 'Душевые ограждения/поддоны',
  'id' => 'santehnika-online.ru/dushevye_ugolki/',
  'url' => 'http://santehnika-online.ru/dushevye_ugolki/',
  'brands' => 
  array (
    0 => '1MarKa',
    1 => 'Appollo',
    2 => 'Alpen',
    3 => 'Bette',
    4 => 'Bravat',
    5 => 'Cezares',
    6 => 'Edelform',
    7 => 'Huppe',
    8 => 'Ideal Standard',
    9 => 'Jacob Delafon',
    10 => 'Kaldewei',
    11 => 'Kolpa San',
    12 => 'Lagard',
    13 => 'Laufen',
    14 => 'Luxus',
    15 => 'Migliore',
    16 => 'Niagara',
    17 => 'Orans',
    18 => 'Radaway',
    19 => 'Riho',
    20 => 'Roltechnik',
  ),
));?>